name: anime_alive
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  adaptive_widgets_flutter: ^0.1.5
  go_router: ^16.1.0
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  json_annotation: ^4.9.0
  google_nav_bar: ^5.0.7





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


  
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-700.ttf
          weight: 700
        - asset: fonts/Raleway-800.ttf
          weight: 800
        - asset: fonts/Raleway-600.ttf
          weight: 600
        - asset: fonts/Raleway-500.ttf
          weight: 500
        - asset: fonts/Raleway-300.ttf
          weight: 300
        - asset: fonts/Raleway-100.ttf
          weight: 100
        - asset: fonts/Raleway-200.ttf
          weight: 200
        - asset: fonts/Raleway-400.ttf
          weight: 400
        - asset: fonts/Raleway-900.ttf
          weight: 900
        
          
       
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
